/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLogInImport } from './routes/auth/log-in'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLogInRoute = AuthLogInImport.update({
  id: '/auth/log-in',
  path: '/auth/log-in',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/log-in': {
      id: '/auth/log-in'
      path: '/auth/log-in'
      fullPath: '/auth/log-in'
      preLoaderRoute: typeof AuthLogInImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/log-in': typeof AuthLogInRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/log-in': typeof AuthLogInRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/log-in': typeof AuthLogInRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/log-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/log-in'
  id: '__root__' | '/' | '/auth/log-in'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLogInRoute: typeof AuthLogInRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLogInRoute: AuthLogInRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/log-in"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/log-in": {
      "filePath": "auth/log-in.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
